@TM:1289711579
@N: FP130 :"":0:0:0:-1|Promoting Net clk_c on CLKBUF  clk_pad 
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@W: MT420 :"":0:0:0:-1|Found inferred clock io_controller|clk with period 10.00ns. A user-defined clock should be declared on object "p:clk"
@TM:1289711575
@N: CG364 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\io_controller.v":2:7:2:19|Synthesizing module io_controller
@TM:1289713344
@A: CL106 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\io_controller.v":48:0:48:5|M
@W: CL113 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\io_controller.v":48:0:48:5|M
@W: CL113 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\io_controller.v":48:0:48:5|M
@TM:1289713502
@W: CL118 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\io_controller.v":48:0:48:5|M
@W: CL118 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\io_controller.v":48:0:48:5|M
