@TM:1297740509
@N: FP130 :"":0:0:0:-1|Promoting Net u3.u0.shift_reset on CLKINT  I_2 
@N: FP130 :"":0:0:0:-1|Promoting Net pld_ctr4_c on CLKBUF  pld_ctr4_pad 
@TM:1290103822
@N: FP130 :"":0:0:0:-1|Promoting Net u3.pc_poll_done on CLKINT  u3.u0.poll_done_inferred_clock 
@TM:1287437265
@N: MF249 :"":0:0:0:-1|Running in 32-bit mode.
@N: MF258 :"":0:0:0:-1|Gated clock conversion disabled 
@TM:1289769266
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@TM:1297740509
@W: MT420 :"":0:0:0:-1|Found inferred clock jtag_pc_poll|poll_done_inferred_clock with period 10.42ns. A user-defined clock should be declared on object "n:u3.u0.poll_done"
@W: MT420 :"":0:0:0:-1|Found inferred clock main|u0.u0.mcu_osc_inferred_clock with period 10.42ns. A user-defined clock should be declared on object "n:mcu_osc"
@TM:1290107633
@W: MT420 :"":0:0:0:-1|Found inferred clock main|pld_ctr4 with period 10.42ns. A user-defined clock should be declared on object "p:pld_ctr4"
@W: MT420 :"":0:0:0:-1|Found inferred clock function_search|done_inferred_clock with period 10.42ns. A user-defined clock should be declared on object "n:u3.u1.u2.done"
@TM:1290029015
@W: MT420 :"":0:0:0:-1|Found inferred clock main|u0.u0.osc6m_inferred_clock with period 10.42ns. A user-defined clock should be declared on object "n:osc6m"
@TM:1289769266
@W: MT420 :"":0:0:0:-1|Found inferred clock main|u0.u0.osc96m_inferred_clock with period 10.42ns. A user-defined clock should be declared on object "n:osc96m"
@TM:1289752967
@N: CG364 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\igloo.v":276:7:276:12|Synthesizing module PLLINT
@N: CG364 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\igloo.v":1163:7:1163:9|Synthesizing module GND
@N: CG364 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\igloo.v":1283:7:1283:9|Synthesizing module INV
@N: CG364 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\igloo.v":1864:7:1864:9|Synthesizing module VCC
@N: CG364 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\igloo.v":1996:7:1996:12|Synthesizing module RAM4K9
@N: CG364 :"C:\Actel\Libero_v9.0\Synopsys\synplify_D200912A\lib\proasic\igloo.v":2447:7:2447:9|Synthesizing module PLL
@TM:1289854446
@N: CG364 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\clock_manager.v":3:7:3:19|Synthesizing module clock_manager
@TM:1297740509
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\clock_manager.v":39:0:39:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\clock_manager.v":49:0:49:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\clock_manager.v":59:0:59:5|M
@W: CL260 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\clock_manager.v":81:0:81:5|M
@W: MO129 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\clock_manager.v":81:0:81:5|M
@TM:1289925612
@N: CG364 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\function_search.v":27:7:27:21|Synthesizing module function_search
@W: CL159 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\function_search.v":45:13:45:21|M
@W: CG133 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\function_search.v":53:10:53:19|M
@W: CG133 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\function_search.v":54:10:54:12|M
@W: CG133 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\function_search.v":55:10:55:12|M
@A: CL153 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\function_search.v":55:10:55:12|M
@W: CG133 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\function_search.v":56:10:56:12|M
@TM:1297740509
@N:  :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\function_search.v":61:0:61:5|M
@W: CL113 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\function_search.v":61:0:61:5|M
@W: CL251 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\function_search.v":61:0:61:5|M
@TM:1290107633
@N: CG364 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\io_controller.v":2:7:2:19|Synthesizing module io_controller
@N: CL201 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\io_controller.v":53:0:53:5|M
@N: CG364 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\jtag_controller.v":2:7:2:21|Synthesizing module jtag_controller
@W: CL159 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\jtag_controller.v":25:6:25:15|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@A: BN291 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":84:0:84:5|M
@W: BN132 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_controller.v":109:0:109:5|M
@TM:1297740509
@N: CG364 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\jtag_pc_poll.v":1:7:1:18|Synthesizing module jtag_pc_poll
@A:  :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\jtag_pc_poll.v":47:0:47:5|M
@N: CL201 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\jtag_pc_poll.v":47:0:47:5|M
@W: MO161 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_pc_poll.v":47:0:47:5|M
@N: CG364 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\jtag_shift.v":59:7:59:16|Synthesizing module jtag_shift
@A:  :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\jtag_shift.v":99:0:99:5|M
@N:  :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\jtag_shift.v":99:0:99:5|M
@A: CL106 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\jtag_shift.v":99:0:99:5|M
@N: CL201 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\jtag_shift.v":99:0:99:5|M
@N: CG179 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\jtag_shift.v":178:23:178:25|M
@N: CG179 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\jtag_shift.v":217:23:217:25|M
@N: CG179 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\jtag_shift.v":258:23:258:25|M
@N: CG364 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\main.v":2:7:2:10|Synthesizing module main
@N: CG364 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\mem_manager.v":2:7:2:17|Synthesizing module mem_manager
@W: CL159 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\mem_manager.v":22:6:22:17|M
@N: BN115 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\mem_manager.v":49:21:49:22|M
@N: CG364 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\output_buffer.v":2:7:2:19|Synthesizing module output_buffer
@W: CL159 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\output_buffer.v":18:6:18:14|M
@W: CL159 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\output_buffer.v":19:6:19:8|M
@N: CG364 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\hdl\program_table_loader.v":2:7:2:26|Synthesizing module program_table_loader
@N:  :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\program_table_loader.v":22:0:22:5|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\hdl\program_table_loader.v":22:0:22:5|M
@N: CG364 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\smartgen\clocks\clocks.v":5:7:5:12|Synthesizing module clocks
@N: CG364 :"C:\Documents and Settings\Administrator\My Documents\actel\TDB_FPGA\smartgen\program_table_mem\program_table_mem.v":5:7:5:23|Synthesizing module program_table_mem
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\smartgen\program_table_mem\program_table_mem.v":17:8:17:29|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\smartgen\program_table_mem\program_table_mem.v":38:8:38:29|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\smartgen\program_table_mem\program_table_mem.v":59:8:59:29|M
@N: BN116 :"c:\documents and settings\administrator\my documents\actel\tdb_fpga\smartgen\program_table_mem\program_table_mem.v":83:8:83:29|M
